name: Auto Tag
on:
  push:
    tags:
      - '*'
      - '!*-veil'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Make Edits
      run: node scripts/index.js
    - name: Tag and push current repo code
      run: |
        git tag ${{env.RELEASE_VERSION}}-veil
        git push origin ${{env.RELEASE_VERSION}}-veil
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{env.RELEASE_VERSION}}-veil