name: Auto Tag
on:
  push:
    tags:
      - '*'
      - '!*-veil'
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Tag and push current repo code
        run: |
          git tag ${{RELEASE_VERSION}}-veil
          git push origin ${{github.run_id}}-veil